- ffmpeg/__init__.py
Add "cmd" argument to run that allows to provide different command for ffmpeg (e.g. you may want to use `avconv` or a wrapper).
> Allow to use different command other than 'ffmpeg'

- ffmpeg/_ffmpeg.py
- ffmpeg/_run.py
- ffmpeg/nodes.py
Assertions are ignored if the interpreter is run with the `-O` (optimize).
I converted all assertions outside of tests to normal exceptions.
Please review the type of the exceptions (maybe we could define some new, module-specific ones), I tried to use the most meaningful ones (basically all `ValueError` and one `RuntimeError`).
> Convert assertions to if+raise

- .travis.yml
Looks like he started using "release" in the link, instead of the most recent version number which changes over time.
edit-
I noticed https://johnvansickle.com/ffmpeg/releases/ffmpeg-3.3.4-64bit-static.tar.xz would work too.         https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz would just be one fewer line to keep up to date
> Update ffmpeg build URL

- .travis.yml
- tox.ini
Remove python 3.3 support since pytest seems to no longer support 3.3.
> Remove python 3.3 support

- ffmpeg/_run.py
- ffmpeg/tests/test_ffmpeg.py
Creating an input with `ss=0` caused the value to be left off of the command-line after `-ss`:
```
In : (ffmpeg.input('in', ss=0).output('out').get_args())
Out: [u'-ss', u'-i', 'in', 'out']
```
With this fix:
```
In : (ffmpeg.input('in', ss=0).output('out').get_args())
Out: [u'-ss', u'0', u'-i', 'in', 'out']
```
> Fix issue with input ss=0

- ffmpeg/_filters.py
Fixes issue mentioned in #64 sample code
> Add `filter_multi_output` to `__all__` so it's available in API

- ffmpeg/_view.py
Prevent leaving unwanted files.
Uses this option:
https://github.com/xflr6/graphviz/blob/master/graphviz/files.py#L192
> Cleanup graph source file after rendering graph to pdf

- ffmpeg/_filters.py
- ffmpeg/nodes.py
- ffmpeg/tests/test_ffmpeg.py
> Add `asplit` filter

- ffmpeg/__init__.py
- ffmpeg/_probe.py
- ffmpeg/tests/test_ffmpeg.py
Adds convenient ffprobe support. Example - print duration of file:
```python
import ffmpeg
print(ffmpeg.probe('in.mp4')['format']['duration']))
```
> Add ffprobe support

- ffmpeg/_run.py
- ffmpeg/tests/test_ffmpeg.py
> Fix `-map` to not use brackets for passthroughs; fixes #102, #23

- ffmpeg/_probe.py
ffmpeg.<stream>.run() method has a `cmd` argument for selecting `ffmpeg` executable.
This simple hack adds this feature to the probe command.
This solves #122
> Added ffmpeg.probe 'cmd' argument

- examples/README.md
- examples/tensorflow_stream.py
- ffmpeg/_run.py
- ffmpeg/tests/test_ffmpeg.py
This adds a `run_async` operator to run ffmpeg asynchronously.
I merged your changes onto another branch and made some adjustments, as described above.
Examples:
- [Input streaming](https://github.com/kkroening/ffmpeg-python/blob/run-async/ffmpeg/_run.py#L209)
- [Output capturing](https://github.com/kkroening/ffmpeg-python/blob/run-async/ffmpeg/_run.py#L218)
- [Tensorflow streaming / numpy processing](https://github.com/kkroening/ffmpeg-python/tree/master/examples#tensorflow-streaming)
- [RTSP input + TCP socket output](https://github.com/kkroening/ffmpeg-python/tree/run-async/examples#stream-from-rtsp-server-to-tcp-socket).
Credit to @Nitaym for some of the ideas + examples on this. Thanks @Nitaym!
> Add `run_async` operator

- .travis.yml
Small change to fix the link for downloading a static build of ffmpeg in CI.
> Fix CI issue with ffmpeg download link

- ffmpeg/_probe.py
- ffmpeg/_run.py
- ffmpeg/_utils.py
- ffmpeg/tests/test_ffmpeg.py
> Ability to accept extra arguments for ffmpeg.probe command (Issue #187)

- ffmpeg/_filters.py
Simple typo fix to docstring of function filter() in filters.py.
> Fix typo "fmpeg-python" to read "ffmpeg-python"

- ffmpeg/_utils.py
- ffmpeg/tests/test_ffmpeg.py
For instance, add multiple `streamid` in the output can be done like this:
```python
ffmpeg.input(url).output('video.mp4', streamid=['0:0x101', '1:0x102'])
```
will output this command line
`ffmpeg -i video.mp4 -streamid 0:0x101 -streamid 1:0x102 video.mp4`
Related to #285
> Duplicate parameters can be set in kwargs with an iterator

- examples/README.md
Just noticed a small bug in the examples readme. The example itself seems correct.
> tensorflow streaming typo

- .travis.yml
- tox.ini
Python 3.4 is end of life...  Should we drop support for it?
> Travis CI and tox.ini: Add Python 3.7 to the testing

- ffmpeg/_probe.py
- ffmpeg/tests/test_ffmpeg.py
Popen.communicate() supports a timeout argument which is useful in case
there is a risk that the probe hangs indefinitely.
> Add optional timeout argument to probe

- ffmpeg/_run.py
Fixes #195 
Redirect stdout/stderr to DEVNULL when quiet is requested, otherwise, the buffer will be filled until a MemoryError on long encodings.
> Fix issue #195. Redirect stdout/err to /dev/null

- ffmpeg/_run.py
> Fix typo in _run.py docstring

- ffmpeg/_run.py
- ffmpeg/tests/test_ffmpeg.py
Implemented the cwd parameter for run, run_async and compile functions.
Changing the working directory is useful when you spawn ffmpeg from multiple threads but each instance has to parse a list of relative paths, think of m3u8 playlists downloaded with aria2.
> Implemented cwd parameter

- ffmpeg/_run.py
- ffmpeg/tests/test_ffmpeg.py
Reverts kkroening/ffmpeg-python#430
Reverting cause it broke CI builds. @Jacotsu can you please double-check it?
> Revert "Implemented cwd parameter"

- ffmpeg/_run.py
- ffmpeg/tests/test_ffmpeg.py
Reverts kkroening/ffmpeg-python#493
It turns out that the issue is not caused by the PR, reverting the revert.
> Revert "Revert "Implemented cwd parameter""

- ffmpeg/_ffmpeg.py
- ffmpeg/_filters.py
- ffmpeg/_run.py
- ffmpeg/_utils.py
- ffmpeg/_view.py
- ffmpeg/dag.py
- ffmpeg/nodes.py
- ffmpeg/tests/test_ffmpeg.py
- pyproject.toml
I've been away for quite some time (things came up, sorry) and am just getting back up to speed on the issues and PRs that have arisen. As preparation for other changes, this PR re-applies Black formatting and wraps docstrings at a more reasonable ~88 columns, matching [Black's default line length](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length).
It seems that CI is failing on master, but this PR doesn't change anything other than code formatting, so I'll probably end up merging it despite the CI failure, and then hopefully be able to fix CI next/soon. FWIW, tests at least seem to pass with 2.7.18 and 3.9.6 running locally on an M1 Mac - just that some of the other Python versions seem to fail in CI in tox's matrix testing.
> Re-apply Black formatting, and wrap docstrings at ~88 columns.

- .github/workflows/ci.yml
CI has started failing due to the following error when attempting to run Black:
```
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/work/_actions/psf/black/21.12b0/.black-env/lib/python3.8/site-packages/click/__init__.py)
```
The issue is described in [Stack Overflow #71673404](https://stackoverflow.com/questions/71673404). But it's only problematic because of being tied to an older version of Black to support ancient Python 2.7 syntax.
We really need to kill off Python 2.7 support; but that's for a separate PR. This just stabilizes things for the time being.
> Fix Black in GHA for Python 2.7
